$ANSIBLE_VAULT;1.1;AES256
36643736393539643763363331633536633461383234633031333336616638393566613666613963
3239653066623030306438353934666564616533366136300a646531323466373161373734313335
32656133343734393264643537306466366130333637323834353263396633373330643536353266
6130623338396464320a613731313830346466363061613065383638656132336336663638656564
36333562376637326362353232333663353664313366316238613631633534326336313161386136
35306439663965383762363161376439383035313733353134653839383461633432623366623061
30323032353536623963326230313464343638653732316533386462303836643238356534303038
66646462326330623736323539376166626538643539663130396234346637336132653337653630
37626333363634316363393337343433353162656165643136303331623233666531373430353735
6337633533303261303330653666663238356434386366356436
